### ISSUE TITLE
Tracing: nested property in object intializer not traced

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#344]
# Update

Bug fix generates error messages in `dbux-runtime`:

* [x] run express#1 and observe output
  > [DBUX traceVisitors] config override at path - old: { originalIsParent: true } , new: { array: true }
* [x] enable `Verbose`
* [x] try to find the main culprit
* [x] write minimal test case, and add sample for further testing (to speed up testing)
* [x] once done, check again on express#1

* [x] As a general guideline: Always test instrumentation changes on `express#1` and `eslint#1`, and take a close look at the output

# Original report

**Steps to reproduce**

* run `objectInit1.js`
* select props of `o1` or `o2`

-> won't select, but property exists

**Relevant code**

In `traceVisitors`:

```js
ObjectExpression: [
      NoTrace,
      [['properties',
        [['value', ExpressionValue]]
      ]]
    ],
```

**Comment by Domiii** [comment]
After merging, instrumentation generates error messages when running it on express:

> [DBUX traceVisitors] config override at path - old: { originalIsParent: true } , new: { array: true }
> [DBUX traceVisitors] config override at path - old: { originalIsParent: true } , new: { array: true }
> [DBUX traceVisitors] config override at path - old: { originalIsParent: true } , new: { array: true }
> [DBUX traceVisitors] config override at path - old: { originalIsParent: true } , new: { array: true }
> [DBUX traceVisitors] config override at path - old: { originalIsParent: true } , new: { array: true }

**Comment by edisonhello** [comment]
Need to check again later if eslint works or not.
