### ISSUE TITLE
Pathways reports errors when re-opening a previously run project

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#540]
## Steps to reproduce (I guess):

1. Run bug from some project (e.g. `express#1`)
2. Restart VSCode
3. See reported errors

## TODO

* [ ] improve error reporting (so we can hunt this down more easily in the future)
  * Probably want to wrap session reload in a `try/catch`  at the very least.
  * Use `NestedError` if you want to re-throw
* [x] fix error messages
* [x] make sure that after restart runtime data is reconstructed correctly, call graph is displayed correctly etc.
* [ ] while loading PDP data, show a cancellable progress bar (it can take very long)

## Error log #1 (happens after re-load)

> [Dbux PracticeManager] getDbuxPath(), relativePath='@dbux/cli/bin/dbux.js', getDbuxRoot()='D:/code/dbux', config={"dependencyRoot":"d:/code/dbux","projectsRoot":"d:/code/dbux/dbux_projects","dbuxLanguage":"en"}
> [Dbux installUtil] Checking library dependencies. Found 0 missing: 
> [Dbux PathwaysDataProvider] Failed to load from log file: Error: Unable to process PDP.collections.userActions: could not find application of trace (applicationId=2). allApplications=[
>   "App #1 @d:\\code\\dbux\\dbux_projects\\todomvc-es6\\src\\helpers.js"
> ]
> 	at UserActionCollection.resolveVisitedStaticTracesIndex (d:\code\dbux\dbux-code\dist\bundle.js:32542:15)
> 	at UserActionCollection.postAddProcessed (d:\code\dbux\dbux-code\dist\bundle.js:32529:10)
> 	at PathwaysDataProvider._postAdd (d:\code\dbux\dbux-code\dist\bundle.js:16132:18)
> 	at PathwaysDataProvider.addData (d:\code\dbux\dbux-code\dist\bundle.js:16059:10)
> 	at PathwaysDataProvider.addData (d:\code\dbux\dbux-code\dist\bundle.js:32934:11)
> 	at PathwaysDataProvider.addNewUserAction (d:\code\dbux\dbux-code\dist\bundle.js:32923:10)
> 	at d:\code\dbux\dbux-code\dist\bundle.js:32346:9
> 	at Array.forEach (<anonymous>)
> 	at resolvePathwaysData (d:\code\dbux\dbux-code\dist\bundle.js:32345:11)
> 	at PathwaysDataProvider.2 (d:\code\dbux\dbux-code\dist\bundle.js:32334:5)
> 	at PathwaysDataProvider.load (d:\code\dbux\dbux-code\dist\bundle.js:32933:509)
> 	at PathwaysDataProvider.init (d:\code\dbux\dbux-code\dist\bundle.js:32929:32)
> 	at ProjectsManager._resetPracticeSession (d:\code\dbux\dbux-code\dist\bundle.js:28875:14)
> 	at ProjectsManager.recoverPracticeSession (d:\code\dbux\dbux-code\dist\bundle.js:28879:471)
> 	at ProjectsManager.init (d:\code\dbux\dbux-code\dist\bundle.js:28853:181)
> 	at d:\code\dbux\dbux-code\dist\bundle.js:9766:26
> [Dbux PracticeManager] Unable to load PracticeSession: Error: Unable to process PDP.collections.userActions: could not find application of trace (applicationId=2). allApplications=[
>   "App #1 @d:\\code\\dbux\\dbux_projects\\todomvc-es6\\src\\helpers.js"
> ]
> 	at UserActionCollection.resolveVisitedStaticTracesIndex (d:\code\dbux\dbux-code\dist\bundle.js:32542:15)
> 	at UserActionCollection.postAddProcessed (d:\code\dbux\dbux-code\dist\bundle.js:32529:10)
> 	at PathwaysDataProvider._postAdd (d:\code\dbux\dbux-code\dist\bundle.js:16132:18)
> 	at PathwaysDataProvider.addData (d:\code\dbux\dbux-code\dist\bundle.js:16059:10)
> 	at PathwaysDataProvider.addData (d:\code\dbux\dbux-code\dist\bundle.js:32934:11)
> 	at PathwaysDataProvider.addNewUserAction (d:\code\dbux\dbux-code\dist\bundle.js:32923:10)
> 	at d:\code\dbux\dbux-code\dist\bundle.js:32346:9
> 	at Array.forEach (<anonymous>)
> 	at resolvePathwaysData (d:\code\dbux\dbux-code\dist\bundle.js:32345:11)
> 	at PathwaysDataProvider.2 (d:\code\dbux\dbux-code\dist\bundle.js:32334:5)
> 	at PathwaysDataProvider.load (d:\code\dbux\dbux-code\dist\bundle.js:32933:509)
> 	at PathwaysDataProvider.init (d:\code\dbux\dbux-code\dist\bundle.js:32929:32)
> 	at ProjectsManager._resetPracticeSession (d:\code\dbux\dbux-code\dist\bundle.js:28875:14)
> 	at ProjectsManager.recoverPracticeSession (d:\code\dbux\dbux-code\dist\bundle.js:28879:471)
> 	at ProjectsManager.init (d:\code\dbux\dbux-code\dist\bundle.js:28853:181)
> 	at d:\code\dbux\dbux-code\dist\bundle.js:9766:26
> [Dbux Call Graph HostWrapper] client connected. - Starting host...
> [Dbux PathwaysDataProvider] writeAll - actionGroups: 1
> [Dbux PathwaysDataProvider] writeAll - userActions: 1

## Another one (after (re-)running a bug)

> Cannot write header of application log file at d:\code\dbux\dbux-code\logs\8cc4b421-2fc1-4640-94ff-7de2be6392f5.dbuxapp

**Comment by Domiii** [comment]
Previously reported in #531

**Comment by Domiii** [comment]
@MiccWan I close this for now. Do you agree that this has been taken care of?
