### ISSUE TITLE
fix and improve value rendering

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#685]
## TODO

* [x] to better investigate the bug of `constructValueObjectShallow` and `constructValueFull` add a way to investigate their "raw data" in `DebugTDNode`
  *  expose all relevant data and their connections, if possible
  * consider `AsyncTDNode.makePromiseLinkTree`: it also gathers all relevant data to visualize a complex (recursive and non-linear) hidden data structure
* [x] fix `omitted` value rendering

## More Issues

* [x] Test + fix error handling: when an object's children's serialization errors out, is the error message is readable in the object's `prop`?
  * [x] find a way to easily reproduce, maybe:
    ```js
    var o = eval(`({ x:1, get y() { throw new Error('Y FAILED'); } })`);
    console.log(o);
    ```
* [ ] future work: change how we iterate `keys`. It currently ignores class getters and more.
  
## Examples

* see this `options` object from `sequelize#5`...
  * NOTE: I reloaded from file. Not sure, if its related to that, or just a bug in Value rendering?
  ![image](https://user-images.githubusercontent.com/282899/154977030-dc3c7ed2-0c8c-431a-af19-9484ae40452a.png)
* same thing happens with only parts of the `document.location` object in `todomvc`:
  ![image](https://user-images.githubusercontent.com/282899/155110941-8b8824b8-bedc-48e8-a3c7-efd6266bf43b.png)

**Comment by MiccWan** [comment]
The valueRef of the child nodes are actually `Omitted`, which is not rendered correctly. I've fix the rendering of omitted values. But the reason they are omitted is still not found yet.

Note: There are some 'ReadError' while serializing `TextDecoder`.
