### ISSUE TITLE
✅Checklist✅: Pathways + User Feedback Collection (2022/4)

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#712]
# Collection

* [ ] https://github.com/Domiii/dbux/issues/436
* [ ] add new commands:
  * `Dbux Pathways: Start`
    * start recording any apps, even outside of practice
  * `Dbux Pathways: Stop`
    * stop recording
  * → make sure, the two commands do the same we do for when initializing pathways as part of a practice project
* [ ] make sure **all commands** and buttons are recorded
  * (can we automatically) generate a list of all commands and buttons?

#  Visualization

* [ ] small "colored bar" when expanding a CG context
  * might help us find out when someone compares CG nodes
  * but don't count it toward the context's time
